name: fowlerfilms
favicon: null
layout_spectrum: 0.8416695825289935
typography_spectrum: 0.8883784124627709
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.3593631461262703
  lightness: 0.8282602417748421
  saturation: 0.6589195234701037
  rhythmicContrast: 0.4025417387019843
purpose: []
